version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - my_network
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    networks:
      - my_network
    depends_on:
      - kafka


  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data_node1:/var/lib/cassandra
    networks:
      - my_network
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 5


  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    ports:
      - "9142:9042"
    volumes:
      - cassandra_data_node2:/var/lib/cassandra
    networks:
      - my_network
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    depends_on:
      cassandra-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 5





  master_node:
    build: ./master_node
    container_name: master-node
    ports:
      - "5000:5000"
    environment:
      - CASSANDRA_HOST=cassandra-node1,cassandra-node2
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./master_node:/app
    depends_on:
      kafka:
        condition: service_healthy
      cassandra-node1:
        condition: service_healthy
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  worker_node:
    build: ./worker_node
    container_name: worker-node
    depends_on:
      kafka:
        condition: service_healthy
      cassandra-node1:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    environment:
      - CASSANDRA_HOST=cassandra-node1
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
    volumes:
      - ./worker_node:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - master_node
    restart: always
    volumes: 
      - ./frontend:/app

volumes:
  cassandra_data_node1:
  cassandra_data_node2:


networks:
  my_network:
    driver: bridge
