version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka-node1:
    image: wurstmeister/kafka:latest
    container_name: kafka-node1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - my_network
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-node1:9092"]
      interval: 15s
      timeout: 10s
      retries: 5

  kafka-node2:
    image: wurstmeister/kafka:latest
    container_name: kafka-node2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - my_network
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-node2:9093"]
      interval: 15s
      timeout: 10s
      retries: 5

  kafka-node3:
    image: wurstmeister/kafka:latest
    container_name: kafka-node3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - my_network
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka-node3:9094"]
      interval: 15s
      timeout: 10s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka-node1:9092,kafka-node2:9093, kafka-node3:9094
    networks:
      - my_network
    depends_on:
      - kafka-node1
      - kafka-node2
      - kafka-node3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus-data:/prometheus 
    ports:
      - "9090:9090"
    networks:
      - my_network
    depends_on:
      - cassandra-node1
      - cassandra-node2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana 
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - prometheus

  
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042" 
      - "7070:7070" 
    volumes:
      - cassandra_data_node1:/var/lib/cassandra
      - ./cassandra-config/jmx_prometheus_javaagent.jar:/opt/jmx_prometheus_javaagent.jar
      - ./cassandra-config/cassandra.yml:/opt/cassandra.yml
    networks:
      - my_network
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - JVM_OPTS=-javaagent:/opt/jmx_prometheus_javaagent.jar=7070:/opt/cassandra.yml
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    ports:
      - "9142:9042"  
      - "7071:7070" 
    volumes:
      - cassandra_data_node2:/var/lib/cassandra
      - ./cassandra-config/jmx_prometheus_javaagent.jar:/opt/jmx_prometheus_javaagent.jar
      - ./cassandra-config/cassandra.yml:/opt/cassandra.yml
    networks:
      - my_network
    environment:
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - JVM_OPTS=-javaagent:/opt/jmx_prometheus_javaagent.jar=7071:/opt/cassandra.yml
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-node1:
    container_name: redis-node1
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6379:6379"
    volumes:
      - redis-node1:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
    networks:
      - my_network
    #add healthcheck
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  redis-node2:
    container_name: redis-node2
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6380:6379"
    volumes:
      - redis-node2:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
    networks:
      - my_network

  redis-node3:
    container_name: redis-node3
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6381:6379"
    volumes:
      - redis-node3:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
    networks:
      - my_network
      
  redis-node4:
    container_name: redis-node4
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6382:6379"
    volumes:
      - redis-node4:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
    networks:
      - my_network

  redis-node5:
    container_name: redis-node5
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6383:6379"
    volumes:
      - redis-node5:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
    networks:
      - my_network

  redis-node6:
    container_name: redis-node6
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6384:6379"
    volumes:
      - redis-node6:/bitnami/redis/data
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node1 redis-node2 redis-node3 redis-node4 redis-node5 redis-node6'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      - my_network


  master_node:
    build: ./master_node
    container_name: master-node
    ports:
      - "5000:5000"
    environment:
      - CASSANDRA_HOST=cassandra-node1,cassandra-node2
      - KAFKA_BOOTSTRAP_SERVERS=kafka-node1:9092,kafka-node2:9093,kafka-node3:9094
      - REDIS_HOSTS=redis-node1,redis-node2,redis-node3,redis-node4,redis-node5,redis-node6
    volumes:
      - ./master_node:/app
    depends_on:
      kafka-node1:
        condition: service_healthy
      cassandra-node1:
        condition: service_healthy
      # redis-node1:
      #   condition: service_healthy
    networks:
      - my_network
    #add healthcheck
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://master-node:5000/health"]
    #   interval: 30s
    #   timeout: 10s   
    #   retries: 3 
    #   start_period: 30s




  worker_node1:
    build:
      context: ./worker_node
      dockerfile: Dockerfile.worker1
    container_name: worker-node1
    depends_on:
      kafka-node1:
        condition: service_healthy
      redis-node1:
        condition: service_healthy
      # master_node:
      #   condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-node1:9092,kafka-node2:9093,kafka-node3:9094
      - REDIS_HOSTS=redis-node1,redis-node2,redis-node3,redis-node4,redis-node5,redis-node6
      - WORKER_ID=worker-1
      - PORT=8000
    volumes:
      - ./worker_node:/app
    restart: on-failure

  worker_node2:
    build:
      context: ./worker_node 
      dockerfile: Dockerfile.worker2
    container_name: worker-node2
    depends_on:
      kafka-node1:
        condition: service_healthy
      redis-node1:
        condition: service_healthy
      # master_node:
      #   condition: service_healthy
    ports:
      - "9001:9001"
    networks:
      - my_network
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-node1:9092,kafka-node2:9093,kafka-node3:9094
      - REDIS_HOSTS=redis-node1,redis-node2,redis-node3,redis-node4,redis-node5,redis-node6
      - WORKER_ID=worker-2
      - PORT=9001
    volumes:
      - ./worker_node:/app
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    networks:
      - my_network
    depends_on:
      - master_node
    restart: on-failure
    volumes: 
      - ./frontend:/app

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis-node1:6379
      - REDIS_EXPORTER_USE_CLUSTERMODE=true
    networks:
      - my_network
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
        # condition: service_healthy


  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command: ["--kafka.server=kafka-node1:9092", "--kafka.server=kafka-node2:9093","--kafka.server=kafka-node3:9094"]
    ports:
      - "9308:9308"
    networks:
      - my_network
    depends_on:
      kafka-node1:
        condition: service_healthy
      kafka-node2:
        condition: service_healthy
      kafka-node3:
        condition: service_healthy

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker/

volumes:
  cassandra_data_node1:
  cassandra_data_node2:
  # prometheus-data: 
  grafana-data: 
  redis-node1:
  redis-node2:
  redis-node3:
  redis-node4:
  redis-node5:
  redis-node6:


networks:
  my_network:
    driver: bridge
