global:
  scrape_interval: 5s  
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308'] 
  
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis-node1:6379
        - redis-node2:6379
        - redis-node3:6379
        - redis-node4:6379
        - redis-node5:6379
        - redis-node6:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']  

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: 'cassandra'
    static_configs:
      - targets:
          - cassandra-node1:7070
          - cassandra-node2:7071