global:
  scrape_interval: 5s  

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308'] 
  
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://redis:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']  

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
  # - job_name: 'cassandra'
  #   static_configs:
  #     - targets: ['cassandra-exporter:8081'] 