global:
  scrape_interval: 5s  

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']  # Kafka Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']  # Redis Exporter

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra-node1:9180', 'cassandra-node2:9180']

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
