# Use a slim Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port for the FastAPI app
EXPOSE 9001

# Run the FastAPI application for the worker node
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9001", "--reload"]
